name: null

channels:
  - conda-forge
  - defaults

dependencies:
  - dask=2.30
  - dask-ml=1.7
  - featuretools=0.20
  - hvplot=0.6
  - imbalanced-learn=0.7
  - jupyterlab=2.2
  - jupyterlab-git=0.22
  - lightgbm=3.0
  - matplotlib=3.3
  - nodejs=14.9
  - numba=0.51
  - optuna=2.2
  - pandas=1.1
  - panel=0.10
  - pip=20.2
  - pip:
    - -r file:requirements.txt
  - pyarrow=2.0
  - python=3.8
  - scikit-learn=0.23
  - xgboost=1.2
